### ISSUE TITLE
    except urllib2.HTTPError,e:^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by senvenGOD** [fofapro/fofa-py#8]
Traceback (most recent call last):
  File "E:/pythonProject/fofa-py-master/example/thinkphp_example.py", line 2, in <module>
    import fofa
  File "C:\Users\18172\AppData\Roaming\Python\Python38\site-packages\fofa\__init__.py", line 1, in <module>
    from fofa.client import Client
  File "C:\Users\18172\AppData\Roaming\Python\Python38\site-packages\fofa\client.py", line 42
    except urllib2.HTTPError,e:
                            ^
SyntaxError: invalid syntax

运行环境  py3.8  win11 已经安装了 fofa 还是存在报错。

**Comment by bipol4r** [comment]
pypi的没更新 不要pip install安装
